### ISSUE TITLE
Implement filters tag for xml_to_nexus

### ISSUE THREAD

**Issue by eugenwintersberger** [pni-libraries/libpninexus#26]
Compression is only supported using the `strategy` tag from Jan Kotanski's data server. However, this is not very versatile (in particular not when adding new filters) and is not mentioned in the documentation. Need to implement the filters tag as originally mentioned in the docs.

**Comment by jkotan** [comment]
It would be good to support 'filter' tags which could be added below strategy tag.  This filter tags could have filter_id, index (order of applying), filter parameters/options
